### ISSUE TITLE
Feature Request: Allow using custom Justfile path

### ISSUE THREAD

**Issue by grimnight** [chrisgrieser/nvim-justice#1]
### Checklist

- [X] I have read the README.
- [X] The feature would be useful to more users than just me.

### Feature Requested

I have the following alias in my shell config:
```shell
alias jf= 'just --justfile ~/.Justfile'
```
which I use often.

It would be useful to be able to set custom justfile path in `require("justice").select()`.
Something like: `require("justice").select("~/.Justfile")` for example?

### Problem solved

Being able to use custom justfiles.

### Alternatives

I don't know.

**Comment by chrisgrieser** [comment]
So essentially an option for the `-g` flag? https://just.systems/man/en/global-and-user-justfiles.html?highlight=Global#global-justfile

**Comment by chrisgrieser** [comment]
This is not just to implement, but I do wonder what the best usage pattern for this would be. 

There could be a path as a parameter as you describe, but I can also other approaches useful, such as including both local and global recipes in the selection window. Or a fallback, where it looks for a global Justfile when no local one has been found. 

Since I don't use a global Justfile, could you maybe elaborate your workflow? Like, when/how/for what do you use a global Justfile?

**Comment by chrisgrieser** [comment]
added in latest commit: https://github.com/chrisgrieser/nvim-justice?tab=readme-ov-file#usage
